// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfp16pGS2yrfJ1nDooyztWisT-TBDGUc',
    appId: '1:52476403026:web:0b083ee0f1e6173b17ae8b',
    messagingSenderId: '52476403026',
    projectId: 'livera-6a8d7',
    authDomain: 'livera-6a8d7.firebaseapp.com',
    databaseURL: 'https://livera-6a8d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'livera-6a8d7.firebasestorage.app',
    measurementId: 'G-ERB907164G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3D_k7RzwbLzvIGxwLV50gSWgsUK7pkyw',
    appId: '1:52476403026:android:b63584c066fd290317ae8b',
    messagingSenderId: '52476403026',
    projectId: 'livera-6a8d7',
    databaseURL: 'https://livera-6a8d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'livera-6a8d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZqnJd1qo7hsLzrSyEKcKKcW2LPOduSC8',
    appId: '1:52476403026:ios:dd3dd2b42406022e17ae8b',
    messagingSenderId: '52476403026',
    projectId: 'livera-6a8d7',
    databaseURL: 'https://livera-6a8d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'livera-6a8d7.firebasestorage.app',
    iosBundleId: 'com.example.liveraApp',
  ); 

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZqnJd1qo7hsLzrSyEKcKKcW2LPOduSC8',
    appId: '1:52476403026:ios:dd3dd2b42406022e17ae8b',
    messagingSenderId: '52476403026',
    projectId: 'livera-6a8d7',
    databaseURL: 'https://livera-6a8d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'livera-6a8d7.firebasestorage.app',
    iosBundleId: 'com.example.liveraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyfp16pGS2yrfJ1nDooyztWisT-TBDGUc',
    appId: '1:52476403026:web:a6f4345972a2146f17ae8b',
    messagingSenderId: '52476403026',
    projectId: 'livera-6a8d7',
    authDomain: 'livera-6a8d7.firebaseapp.com',
    databaseURL: 'https://livera-6a8d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'livera-6a8d7.firebasestorage.app',
    measurementId: 'G-13GQH4EBYD',
  );

}